### PR TITLE
err: some necessary changes, because mod crashes the server

### PR DESCRIPTION
**Pull request by zetti68**

### CODE REVIEW

**Comment by zetti68** [comment]
Hello Lion, I changed a little bit once more. The version 1.5/1.6 crashed my server. I changed the the directory for the nbt-file relative to config directory (...client.Minecraft is only available at client) and added the notation @SideOnly(Client) to tickEvent

**Comment by LionZXY** [comment]
Wiki example?

**Comment by LionZXY** [comment]
Ping

**Comment by zetti68** [comment]
Hello Lion,
sorry for late answer, I was in holidays and this week on a bussiness trip.
The wiki example should be in wiki folder. It is commented and adapted to my latest changes.

But I found a new bug. The import of scala...Arrays was wrong and my server crashed with it. I changed it to java.utils.Arrays. That version runs.

Additionally I changed the add/ remove methods to an undoable action. The functions are equal, but minetweaker manage unload and reload of all changed recipies.

I have also a minechem crossover script. Should I add it to wiki folder?

**Comment by LionZXY** [comment]
Yes :) Add, please :3

**Comment by zetti68** [comment]
Here it is :), no problem. Did you find the GT_example.zs? It's in the wiki folder too.

**Comment by LionZXY** [comment]
Yup. Today publish release on curse ;)

**Comment by LionZXY** [comment]
Sorry. Not today :( Wait, please

**Comment by LionZXY** [comment]
I can't compile this version. Is your version exactly compilable?

**Comment by LionZXY** [comment]
Update GT and launch :)

**Pull request merged**
